baseURL = "https://toddjdavis.com/"
languageCode = "en-us"
title = ""
#theme = "ananke"
#theme = "hugo-theme-techdoc"
#theme = "docsy"
#theme = "ace-documentation"
#theme = "compose"
contentDir = "docs"
sectionPagesMenu = "main"
offlineSearch = true

[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]


# For a full list of parameters used in Docsy sites, see:
# https://github.com/google/docsy-example/blob/master/config.toml


[outputFormats]
[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "_print"
permalinkable = false

[outputs]
   home = ["HTML", "RSS","JSON"]


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

#    [[menu.main]]
#        name = "Resume"
#        url = "/resume/"
#        weight = 2


# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[module]
proxy = "direct"
[[module.imports]]
  path = "github.com/google/docsy"
  disable = false
[[module.imports]]
  path = "github.com/google/docsy/dependencies"
  disable = false
