site_name: mrtoad.me
site_url: https://mrtoad.me
remote_branch: master
theme: windmill
plugins:
  - awesome-pages
  - search:
      prebuild_index: True
nav:
  - Home: index.md
  - Resume: resume.md
  - ...

extra:
  disqus:  

#markdown_extensions:
#  - meta
