site_name: mrtoad.me
remote_branch: master
theme: 
  name: material
  logo:
    icon: desktop_mac
site_url: https://mrtoad.me
nav:
  - Home: index.md
  - Resume: resume.md

extra:
  disqus:  mrtoad-me

markdown_extensions:
  - meta
